Repository gardener/machine-controller-manager-provider-gcp, pull requests merged in 2022-07, with the labels that each got.

#49 remove service account validation
  pkg/gcp/machine_controller_util.go
  pkg/gcp/validation/validation.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#41 Adds GPU support
  pkg/api/v1alpha1/provider_spec.go
  pkg/gcp/machine_controller_util.go
  pkg/gcp/validation/validation.go
Labels: needs/ok-to-test, kind/api-change, platform/gcp, reviewed/lgtm, size/s

#50 Change base image from alpine to distroless
  Dockerfile
  Makefile
Labels: needs/ok-to-test, area/security, kind/enhancement, reviewed/lgtm, size/xs

#52 Remove service account validation
  pkg/gcp/validation/validation.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#53 Remove service account validation
  pkg/gcp/validation/validation.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs
