Repository gardener/machine-controller-manager-provider-gcp, pull requests merged in 2023-12, with the labels that each got.

#97 Update go to `1.21.4`
  .ci/pipeline_definitions
  Dockerfile
  go.mod
  go.sum
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/xs

#99 Update testmachinery image location
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#100 switch GCR -> Artifact-Registry
  .ci/pipeline_definitions
  Makefile
  kubernetes/deployment.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, reviewed/lgtm, size/s

#98 Add support for min cpu platform
  kubernetes/machine-class.yaml
  pkg/api/v1alpha1/provider_spec.go
  pkg/gcp/machine_controller_util.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#102 Enhance IT pipeline for GCP
  .ci/pipeline_integration_test
Labels: needs/ok-to-test, reviewed/lgtm, size/s
